In [1]:
import numpy as np

In [40]:
a = np.arange(25).reshape(5, 5)

In [58]:
a

array([[ 0,  2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int8)

In [59]:
a.dtype

dtype('int8')

In [60]:
a.itemsize

1

In [61]:
a.strides

(5, 1)

In [62]:
from numpy.lib.stride_tricks import as_strided

In [63]:
a[0,:3]

array([0, 2, 2], dtype=int8)

In [64]:
as_strided(a, (3,), (4,))

array([0, 4, 8], dtype=int8)

In [65]:
as_strided(a, (14,) )

array([ 0,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int8)

In [66]:
as_strided(a, (25,) ) # flatten

array([ 0,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24], dtype=int8)

In [67]:
as_strided(a, (3,), (8,))

array([ 0,  8, 16], dtype=int8)

In [68]:
as_strided(a, (4,), (20,))

array([ 0, 20, 70,  0], dtype=int8)

In [69]:
as_strided(a, (5,), (0,))

array([0, 0, 0, 0, 0], dtype=int8)

In [70]:
as_strided(a, (3,3), (20,4))

array([[ 0,  4,  8],
       [20, 24, 49],
       [70,  0,  0]], dtype=int8)

In [71]:
a = a.astype('int8')

In [72]:
as_strided(a, (3,3), (1,5)) # transpose

array([[ 0,  5, 10],
       [ 2,  6, 11],
       [ 2,  7, 12]], dtype=int8)

In [77]:
a = np.array([1,2,3,4])
aa = np.array([[1,2],[3,4]])

In [89]:
a

array([1, 2, 3, 4])

In [90]:
aa

array([[1, 2],
       [3, 4]])

In [85]:
np.einsum('x', a)

array([1, 2, 3, 4])

In [74]:
np.einsum('y', a)

array([1, 2, 3, 4])

In [79]:
np.einsum('xy', aa)

array([[1, 2],
       [3, 4]])

In [87]:
np.einsum('yx', aa)

array([[1, 3],
       [2, 4]])

In [80]:
aa

array([[1, 2],
       [3, 4]])

In [81]:
np.einsum('xx', aa)

5

In [82]:
np.einsum('xx->', aa)

5

In [83]:
np.einsum('xx->x', aa)

array([1, 4])

In [84]:
np.einsum('xy->yx', aa)

array([[1, 3],
       [2, 4]])

In [88]:
np.einsum('xy-> ', aa)

10

In [92]:
np.einsum('xy,xy-> ', aa, aa)

30

In [93]:
aa * aa

array([[ 1,  4],
       [ 9, 16]])

In [94]:
np.einsum('xy,xy-> x', aa, aa)

array([ 5, 25])

In [95]:
np.einsum('xy,xy-> y', aa, aa)

array([10, 20])

In [96]:
np.einsum('xy,yx-> ', aa, aa) # 행렬곱의 대각선 합

29

In [97]:
aa @ aa

array([[ 7, 10],
       [15, 22]])

In [98]:
np.einsum('xy,yz -> ', aa, aa)

54

In [99]:
np.einsum('b,b-> ',a,a) # 내적 : a * a 합

30

In [100]:
a * a

array([ 1,  4,  9, 16])

In [101]:
np.einsum('b,b-> b',a,a)

array([ 1,  4,  9, 16])

In [102]:
np.einsum('a,b-> ab',a,a) # 외적

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [103]:
np.einsum('a,bb-> a',a,aa)

array([ 5, 10, 15, 20])

In [104]:
np.einsum('ab,a-> b',aa,a)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2)->(2,2) (4,)->(4) 